### ISSUE TITLE
The leaves are not dropping!

### ISSUE THREAD

**Issue by NaviEsket** [RandomMcSomethin/fallingleaves#19]
I have the default settings and there none leave drops. 
I don´t know what to do.

Regards
Leon

**Comment by Fourmisain** [comment]
Which leaf blocks are you looking at? Not all leaf blocks drop leaves.
Do the leaf blocks show up in under the Leaf Settings?
Also, are you playing on a multiplayer server?

**Comment by Fourmisain** [comment]
Ah and you need to set Particles to at least Minimal under video settings!

**Comment by NaviEsket** [comment]
Ah yeah it was a diffrent modpack so, i noticed it was only default trees falling leaves.

**Comment by Fourmisain** [comment]
Modded trees should work too!

You are probably looking at "conifer trees", basically needle trees like spruce, hemlock, redwood, cypress etc.
We decided that those trees don't drop leaves by default because they don't do that in real life too.

If you want, you can enable leaves from conifer trees by going into the Falling Leaves Mod Menu settings and setting "Conifer Leaf Spawn Rate" to something non-zero.

There's also a small hand full of leaf blocks that have a leaf spawn rate of 0, like palms or shrubs, which you can also set to have a spawn rate greater than 0.

You can find a full list of all the conifer trees [here](https://github.com/RandomMcSomethin/fallingleaves/blob/d5cc5ac3074ef513cab6af56d886c9f1424f2d5d/src/main/java/randommcsomethin/fallingleaves/config/ConfigDefaults.java#L9-L21) and the list of trees with spawn rate 0 [here](https://github.com/RandomMcSomethin/fallingleaves/blob/d5cc5ac3074ef513cab6af56d886c9f1424f2d5d/src/main/java/randommcsomethin/fallingleaves/config/ConfigDefaults.java#L31-L35).

Everything can be adjusted through Mod Menu or the fallingleaves.json config file.

If you find a tree that does not drop leaves even after you configured it, please give me the name so I can look at it.

**Comment by Fourmisain** [comment]
Since it's been 11 days, I'm gonna close this issue for now.

If you are still having issues, simply add a reply or open a new issue.
