### ISSUE TITLE
[Suggestion] Block color integration with the /particle command

### ISSUE THREAD

**Issue by RyanCR03** [RandomMcSomethin/fallingleaves#24]
currently `/particle falling_leaves:falling_leaf` doesnt have a parameter for the block being used
it could be useful to have a block id paramater there that changes the color of the particle just like `minecraft:falling_dust`

**Comment by Fourmisain** [comment]
Gave this one a try and was able to make it work, have some lava leaves!
![lavaleaves](https://user-images.githubusercontent.com/8464472/149359857-5b39c9b7-84f6-42dc-840b-6b00cfe4099f.png)
There's a **big** limitation to this however: This will only work in singleplayer.

That's because the command is executed server-side and since Falling Leaves is a client-side mod, the server doesn't know about the `falling_leaf` particle. There's no way around this except making Falling Leaves a server-side mod too, which simply does not feel right for such a small feature - I think such a command block would then also cause errors on vanilla clients.
So singleplayer is the best I can do here.
