### ISSUE TITLE
whenever I try to play it give me this error message

### ISSUE THREAD

**Issue by thebosskill** [RandomMcSomethin/fallingleaves#5]
![minecraft](https://user-images.githubusercontent.com/74687447/99600171-1e10b780-29ba-11eb-96c9-3231924f05ac.PNG)
could someone help?

**Comment by Fourmisain** [comment]
Do you still have this issue?

This does not look like it's related to this mod at all and the only thing I could find online is this [reddit thread](https://reddit.com/r/ModdedMinecraft/comments/kbxcs8/cant_connect_to_lan_world_with_friend/).

I can only assume you are trying to connect to a server that doesn't have the same mods installed or you are connecting to something which isn't actually a Minecraft server?

Sorry, that's all I can get from this.

Since it's not related to this mod, I'm gonna close this issue now but if you want you can still comment here.

**Comment by thebosskill** [comment]
Thank you for your email, but I was able to fix the issue. Turns out I had
to uninstall Minecraft completely and reinstall it. I think it was an issue
with my files. It’s fixed now. Thank you.
