### ISSUE TITLE
Not *entirely* client-side?

### ISSUE THREAD

**Issue by Wo0fle** [RandomMcSomethin/fallingleaves#54]
Here's the situation:
- I have Falling Leaves mod
- I invite my friends (who DO NOT have Falling Leaves) to join a world using Essential
- They get this message:

![hold up](https://github.com/RandomMcSomethin/fallingleaves/assets/81187812/a80e228c-ec72-4ffa-802b-d9b06ee4120f)

> IGNORE "TCDCOMMONS", THAT'S ANOTHER MOD THAT I REMOVED ANYWAY

However, here's another situation:
- I do not have Falling Leaves mod
- I invite my friends (who DO have Falling Leaves) to join a world using Essential
- They join the world just fine, no issues

I checked Mod Menu and it doesn't list Falling Leaves as "Client", but it seems like it should be.

What is going on? Is this something on my end?

**Comment by Fourmisain** [comment]
Falling Leaves is 100% client-side. I know because I patched it over 2 years ago #3, starting off this whole maintaining business.

I assume this is an inherent issue with the way Essential works and might also be related to some recent Fabric API change...?

When using Essential, you must be connecting to your friend's integrated server and I assume the particles Falling Leaves registers "leak" into the "server-side".

I'm not sure if there's anything we can do about that, since running a true server does allow joining with or without the mod as expected.
(I double checked it right now, setup a 1.20.1 server with Falling Leaves, Fabric API and Cloth Config. Vanilla client can join. Fabric client with just Fabric API can join too.)

The easiest fix is honestly to just install the mod and turning it off - I made on-off button just for occasions like these 😄

**Comment by Wo0fle** [comment]
Good to know! Thanks!

**Comment by Fourmisain** [comment]
Just thought a little bit about it.
It's definitely due to the registry "leaking" into integrated server - because client and it's integrated server use the same one registry.
While it's theoretically possible to spawn particles without using the particle registry, it'd probably require a bunch of hacky code and we'd lose features like the `/particle` command too.

So in the end I think the best course of action is no action at all.
