### ISSUE TITLE
Snow drops when Fabric Seasons is in summer

### ISSUE THREAD

**Issue by vico93** [RandomMcSomethin/fallingleaves#55]
I wonder if this mod "talks" in anyway with @lucaargolo's [Fabric Seasons](https://github.com/lucaargolo/fabric-seasons) when it's installed.
When it's spring/summer on a icy biome, while the snow and ice melt the spruce trees (without a snow layer above the leaves) still give the snow effect below them. I wonder if the mod could detect the current season to stop that snowing (and put regular green particles instead).

![2023-09-04_22 48 22](https://github.com/RandomMcSomethin/fallingleaves/assets/3485505/be85d8ed-c674-47e9-a1ec-0257de2920a6)

**Comment by Fourmisain** [comment]
It does "talk" to Seasons. In fall and winter, leaf spawn rates are affected.

Just checked Seasons' code. The way it melts snow is by increasing the temperature (for certain biomes) in summer.
I originally tried detecting "snowy biomes" via temperature, but that was highly unreliable.
I think it would probably be best to disable the ["snowy villagers" check](https://github.com/RandomMcSomethin/fallingleaves/blob/af7d895c09f45daa084fdbd9253dcc3f810c6c9d/src/main/java/randommcsomethin/fallingleaves/util/LeafUtil.java#L105-L107) if Seasons is in summer, so that the "snow on top of trees" check can work instead.

P.S.
Snow drops are independent from leaf drops and spruce are coniferous, so they wouldn't spawn any particles (by default).

**Comment by Fourmisain** [comment]
New version is up!

**Comment by vico93** [comment]
Thanks a lot!
