### ISSUE TITLE
Config not found in ModMenu

### ISSUE THREAD

**Issue by drippyV2** [RandomMcSomethin/fallingleaves#60]
I can't change any settings for the mode becasue of getting this error: 
![image](https://github.com/RandomMcSomethin/fallingleaves/assets/70470012/765da7d8-b887-4037-b762-3e26f9c8be11)

I also tried uninstalling every other mod I had except the ones needed and falling leaves gives me the same Error tried different version of Falling leaves and the dependencies but still the same.

**Comment by Fourmisain** [comment]
Which Minecraft version are you on?

It says it can't find a certain Minecraft method (`TextFieldWidget.setCursorToStart(boolean)`) which only exists since 1.20.2, so that means you must be on an earlier version but are using mods built for later versions.

This specific error is most likely from Cloth Config, so go for example on [Modrinth](https://modrinth.com/mod/cloth-config/versions?l=fabric) and filter for the Minecraft version you are using:
![filter](https://github.com/RandomMcSomethin/fallingleaves/assets/8464472/65d7dd5d-af22-4534-8e6b-a1953343e235)

For example:
For 1.20.1, you'd use Cloth Config v11.1.118, Mod Menu 7.2.2, Fabric API 0.91.0+1.20.1 and Falling Leaves 1.15.4.
For 1.19.2, you'd use Cloth Config v8.3.115, Mod Menu v4.1.2 (or v4.2.0-beta.2) and Fabric API 0.77.0+1.19.2 and Falling Leaves 1.13.0.

Make sure to delete any other version of Cloth Config and any other mods not built for your Minecraft version, as they may contain Cloth Config as well.

**Comment by drippyV2** [comment]
Cloth Config v11.1.118 worked thank you very much for the help.
