### ISSUE TITLE
Why is bro levitating🙏🙏🙏🙏🙏🙏

### ISSUE THREAD

**Issue by Epik0rangutan** [RandomMcSomethin/fallingleaves#61]
![What's wrong with blud](https://github.com/RandomMcSomethin/fallingleaves/assets/163749224/b95c17d4-2d7b-4e0a-b1cd-8dfc885dd580)

**Comment by Fourmisain** [comment]
Bro just doesn't want to get wet!

**Comment by Fourmisain** [comment]
Leaf Jesus aside for a second,
the reason why the leaves don't really "fall" here is because leaves stop their vertical momentum once they collide with water and the collision check is just a rough block check:
https://github.com/RandomMcSomethin/fallingleaves/blob/75b5ee6f70601d0f30ae988b9860361660106b4a/src/main/java/randommcsomethin/fallingleaves/particle/FallingLeafParticle.java#L82-L84

I remember trying to improve the water collisions ages ago, but it was still janky because the true water collisions are boxy and not as smooth as the water model suggest. Here's a very scientific illustration of what I mean:
![illustration](https://github.com/RandomMcSomethin/fallingleaves/assets/8464472/31a502ad-cd2c-4ee1-a52d-7ef2483e7818)
The leaves would "hickup" when going from one water level to a lower one.

Looks like I didn't even feel the need to keep that experimental code around.
I'll give it some more thought, maybe there's a better way of handling this.

**Comment by Fourmisain** [comment]
I improved the water physics a bit.
Leaves should flow on water, dip up and down a bit ~~and ascend to the heavens when they hit a water fall from the side~~.

New version 1.15.5 is up!
