### ISSUE TITLE
Visual bug in the config

### ISSUE THREAD

**Issue by RaoulPurba** [RandomMcSomethin/fallingleaves#63]
I jokingly add `minecraft:dirt` in the Additional block states that drop leaves, and I saw that there are Dirt in the Additional leaf block settings. And then when I deleted `minecraft:dirt` from the entry, the setting is still there and it's annoying me that Dirt is beside all those leaves 😭

![2024-04-05_07 19 15](https://github.com/RandomMcSomethin/fallingleaves/assets/102407222/dfd55426-8c34-48fb-9058-f8db1a1b0a4e)
![2024-04-05_07 19 35](https://github.com/RandomMcSomethin/fallingleaves/assets/102407222/3c7e5c83-ac20-4a5a-abbc-a9f98bb21453)

**How to recreate:**
1. Open fallingleaves config
2. Go to Experimental tab, and put any block in the Additional block states that drop leaves entry
3. See that there is that block in Leaf Block Settings tab
4. Delete the entry that you put your block in
5. See that that block is still in your Leaf Block Settings tab

If there's any way to access the config so I can delete it myself please inform me. Thanks.

**Comment by Fourmisain** [comment]
Oh right, that is a thing! 😄
I think the easiest fix is to open your Falling Leaves config file (found in the `.minecraft` profile folder under `config/fallingleaves.json`) and delete these lines:
```
    "minecraft:dirt": {
      "spawnRateFactor": 1.0,
      "isConiferBlock": false,
      "spawnBreakingLeaves": true
    },
```

I'm not sure if there's a good general fix for this, since this behavior is _sort of_ intentional.
The idea is to keep all settings around in case you uninstall and later reinstall a mod or enable dirt leaves at some point again.
It only shows up, since we can't be fully sure what is or isn't a leaf block in the main menu.

Maybe I can change it so it doesn't save stuff that uses default values at least? Need to see if that's possible.

**Comment by RaoulPurba** [comment]
Thank you!! Keep up the good work my man.

**Comment by Fourmisain** [comment]
Released a new version which doesn't save default leaf settings.
Still requires a restart to get rid of the entry, but at least it's not permanent anymore.
