### ISSUE TITLE
Crash upon loading when config file is empty

### ISSUE THREAD

**Issue by SouthernPixelYT** [RandomMcSomethin/fallingleaves#64]
[crash-2024-04-29_18.35.06-client.txt](https://github.com/RandomMcSomethin/fallingleaves/files/15155992/crash-2024-04-29_18.35.06-client.txt)

I have the latest cloth config, fabric api, and Falling leaves for 1.19.4 Fabric but when I load up the game it crashes

**Comment by Fourmisain** [comment]
Apparently the config migration fails.
Can you send the `fallingleaves.json` file from the config folder? Would really like to know what's going on with it.

After that you can simply delete the file and the issue should be gone.
Ah and btw, for 1.19.4 you should be using Falling Leaves 1.15.6.

**Comment by SouthernPixelYT** [comment]
Sorry for the late reply. Thanks for not closing my issue due to inactivity. Here is the config json file 
[fallingleaves.json](https://github.com/RandomMcSomethin/fallingleaves/files/15213918/fallingleaves.json)

**Comment by SouthernPixelYT** [comment]
Doing what you said fixed my issue. Thank you!

**Comment by Fourmisain** [comment]
Thanks for coming through with the config!

So let's take a look...
Huh, the config file is empty!
This _is_ what I expected from looking at the code, but at the same time I still have no idea how that empty config even came to be.
Maybe your game crashed at some point while it was writing the config and thus left it empty?

Either way I can finally patch this issue, you weren't the first to run into it I believe.
Probably won't do a backport since it's so rare and easily fixed manually though.

**Comment by Fourmisain** [comment]
The titular issue needs to be fixed in Cloth Config.
In the meantime I released 1.15.8 with a Mixin to patch Cloth Config.
