### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by BrekiTomasson** [RandomMcSomethin/fallingleaves#7]
Has this mod been abandoned? I see several open issues without the repository owner's input, a pull request that hasn't been handled for more than a month, etc... The `LICENSE` file says MIT, so it should be OK for anybody to pick this up, but I want to give @RandomMcSomethin the chance to do the right thing here.

However; if it truly is abandoned, I could imagine picking it up and maintaining it - unless somebody else wants to, of course. Maybe @Fourmisain as they already have a pull request fixing several of the outstanding issues?

**Comment by Fourmisain** [comment]
I was wondering that too; I imagine RandomMcSomethin is just busy and/or didn't bother checking Github.

There has been a mod update on CurseForge to version 1.2 while Github is still on 1.1 - though it's only about 2 lines of code:
> + Added a config option to change how long leaf particles remain in the world

Checking his CurseForge page, there's this message:
> Also, to the people submitting bugs and issues to me: I am very grateful, and I hear you loud and clear!  I will attempt to fix these bugs and issues as I am made aware of them.  There is now an internal issue tracker you can access by clicking the Issues tab on this mod's page, and I ask that all future bugs be reported there so I can find them all in one place.  Thank you!

Which seems to confirm he doesn't use Github out of convenience.

As you pointed out, since the project is licensed under MIT, everyone can fork, modify and redistribute, even without source code.
However, the CurseForge page actually has a "custom license" saying
> Look through my code if you wanna learn from it, but don't steal it.

While certainly not legally binding (what constitutes as "stealing" code?), it may mean RandomMcSomethin doesn't want us to fork the project, so making a "Falling Leaves 2 - Revival Edition" is at least morally questionable.

I opened an [issue on CurseForge](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric/issues/3), hoping to reach.

**Comment by RandomMcSomethin** [comment]
Hello!
Sorry I haven't been responsive; I haven't checked this repo in a long while and didn't realize I was getting notifications.  

As for the project, it's currently on a temporary hiatus as I focus my efforts elsewhere.  However, I am aware there are requests that can't wait on my free whim.  If there is one thing I'm not good at, it's maintaining projects.  

I'd love to have someone else help maintain the project, but I don't really know how to set that up.  Mainly because I've never done it before.  This is my first mod that's gained serious traction.  

Please respond back once you can see this and if you want to help; I'd greatly appreciate it!

Thank you,
 - Random

**Comment by Fourmisain** [comment]
Welcome back!

> Sorry I haven't been responsive; I haven't checked this repo in a long while and didn't realize I was getting notifications.

Happens to all of us, I know it did to me.

> I'd love to have someone else help maintain the project, but I don't really know how to set that up. 

I've also never done that before, so I took a look.

For GitHub, you can add users like BrekiTomasson and me as collaborators under
Settings -> Manage access -> Invite a collaborator

That should allow us to directly commit to the project and do a whole lot of other things according to the [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account).
It doesn't look like GitHub allows to fine tune permissions outside of [organization and enterprise accounts](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/access-permissions-on-github).

As for CurseForge, I found [this](https://authors.curseforge.com/knowledge-base/projects/3446-project-member-management).
So you can add users as project members, in this case probably as "Maintainer" and you can set the permissions as you like.

>  If there is one thing I'm not good at, it's maintaining projects.

I also wouldn't say I'm especially good at maintaining projects because I tend to go missing, but I can still help out while I'm here.
So if you want, you can add us both - is that alright, @BrekiTomasson?

It would also be good if you pushed the code for the latest version 1.2 onto GitHub so we don't have to reimplement it.
Since you merged my pull request just now, you probably need to resolve a merge conflict.
Alternatively, you can just push the 1.2 code to a separate branch and I can resolve it from there.

**Comment by BrekiTomasson** [comment]
I couldn't have said it better myself, @Fourmisain . I'd be happy to help out alongside the both of you on this project. That way, two of us can disappear from the face of the Earth and hopefully the third will be around - because heaven knows I tend to do the very same as well :D

**Comment by RandomMcSomethin** [comment]
Thank you for your help and support!
I'll push the 1.2 code to a separate branch and get permissions set up.  Again, thank you both so much for helping me learn this!

**Comment by Fourmisain** [comment]
Permissions are there, 1.2 is pushed, I guess this "issue" can be closed now!

I merged 1.2, added missing config descriptions and did some cleanup.

I'm not quite ready to push here because I found that `leafRate` (and `coniferLeafRate`) are backwards.
"Rate" means higher is faster, but there were more leaves the _lower_ leafRate is - with the exception of 0, which is no leaves.
It's like those ovens that go from 0 to 3, 2, 1, except in that case there's a technical reason behind it.

I changed
 https://github.com/RandomMcSomethin/fallingleaves/blob/c97c06fb6a365170d15804ca4f7738a5952dd6fc/src/main/java/fallingleaves/fallingleaves/mixin/LeafTickMixin.java#L37
to this
```
if (rate != 0 && random.nextDouble() < 1.0 / (75/rate)) {
```
which also does not need to round.
This does mean the rate is limited by 75 since the right side becomes > 1, but that's fine since a rate that high is overkill anyways.

The thing is that changing the meaning of the setting will change the actual leaf rate of all users with custom settings (default settings are unaffected at least).
I don't think AutoConfig has a way of migrating configs, so it's either pushing through and adding a warning to the next release or reverting the change and living with the backwardness.

[This](https://github.com/Fourmisain/fallingleaves/commits/1.16.4) would be what I want to push.

Objections?

**Comment by RandomMcSomethin** [comment]
No objections from me!  Apologies if things are a bit sloppy, as I'm still trying to get things together 😅

**Comment by Fourmisain** [comment]
Just uploaded 1.3.

@RandomMcSomethin Maybe you want to update the mod description on CurseForge as well, so people know you're on hiatus.
I'd rather not delete your text (the part in green) myself.

**Comment by Fourmisain** [comment]
Dear god, what's going on with CurseForge?
I saw your new description wanted to edit in "client-side mod" and it showed me the old description.
So I thought it just needed some time, did some other stuff, came back and now the description reverted to the old one but going to edit it showed the new one?

I made a backup just to be sure, I hope everything is alright now.

(Also, `leafRate` and `coniferRate` wasn't in the official 1.2 version, so there's nothing to worry about)
